# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-12 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scotrailID', models.CharField(max_length=10)),
                ('tracsisID', models.CharField(max_length=10)),
                ('surveyDate', models.DateField()),
                ('scannedDate', models.DateField()),
                ('keyedDate', models.DateField()),
                ('checkedDate', models.DateField()),
                ('convertedDate', models.DateField()),
                ('surveyed', models.BooleanField()),
                ('scanned', models.BooleanField()),
                ('keyed', models.BooleanField()),
                ('checked', models.BooleanField()),
                ('converted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='JourneyStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopType', models.CharField(max_length=1)),
                ('arrTime', models.TimeField()),
                ('depTime', models.TimeField()),
                ('actualArrTime', models.TimeField()),
                ('actualDepTime', models.TimeField()),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Journey')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='journeystop',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trains.Station'),
        ),
    ]
